# Site settings
# -------------
baseurl : /syllabus # the subpath of your site, e.g. /blog
colour  : primary
language: nl

# SEO
# ---
title      : &title SLLBS
description: Style Guide for Syllabi.
author     : Olivier Parent
# url        :
# image      :

# Build settings
# --------------
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed
exclude:
  - gulpfile
  - node_modules/
  - src/
  - Gemfile
  - LICENSE
  - package.json
  - README.md