# OLOD's
destinations:
  - artestead-doc
  - cmp
  - dotfiles-doc
  - ed
  - mapps
  - mma
  - mapps
  - nmdad2
  - nmdad3
  - wanm
  - webd1
  # - test

# Directories
dir:
  node: ./node_modules/
  src : ./src/

# gulp-sass
# @link https://www.npmjs.com/package/gulp-sass
# @link https://github.com/sass/node-sass
sass:
  development:
    includePaths: &includePaths
      - ./node_modules/bootstrap/scss
      - ./_sass
  production:
    includePaths: *includePaths
    outputStyle : compressed

# gulp-uglify
# @link https://www.npmjs.com/package/gulp-uglify
# @link https://github.com/mishoo/UglifyJS
uglify:
  mangle          : true
  preserveComments: license
